version: '3.4'

services:
    db:
      image: mysql:5.7
      volumes:
          - dbdata:/var/lib/mysql
      restart: always
      environment:
        MYSQL_DATABASE: DAYTRADING
        MYSQL_USER: root
        MYSQL_PASSWORD: root
    transaction-server:
      build: .
      restart: always
      ports: 
        - "9090:9090"
      depends_on:
        - db
      links:
        - db 

volumes:
  dbdata: